packages/@ember/octane-addon-blueprint/files/.ember-cli.js, packages/@ember/octane-app-blueprint/files/.ember-cli.js
Required by `Update blueprints for each object type to use native JS classes` of the [Octane Tracking Issue](https://github.com/emberjs/ember.js/issues/17234)
=> Set `EMBER_VERSION` env variable to `OCTANE`

packages/@ember/octane-addon-blueprint/files/package.json
`classProperties` could not be used in the `src` folder of the addon directory, but it could on the `tests/*`.
```
Build Error (broccoli-persistent-filter:Babel > [Babel: oct-addon1]) in oct-addon1/src/services/hola.js
oct-addon1/src/services/hola.js: Support for the experimental syntax 'classProperties' isn't currently enabled (4:8):
2 | 
3 | export default class HolaService extends Service {
> 4 |   val1 = 'hola - service';
|        ^
5 | }
6 | 
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```
Moving `@ember-decorators/babel-transforms` from `devDependencies` to `dependencies` solved the issue.
It was commented at https://github.com/ember-decorators/ember-decorators/issues/134#issuecomment-31709 …
=> Move `babel-transforms` to `dependencies` list

README.md
Added an example on the Readme for the Glimmer component API.
`babel-plugin-ember-modules-api-polyfill 2.7.0` is automatically installed with the blueprint;  the Glimmer API works 🎆
Pending to bump `ember-cli-babel` when released: https://github.com/ember-cli/ember-rfc176-data/pull/113
Should the Readme of the `sparkles-component` being updated to recommend using this setup instead?
cc @rwjblue
=> Added `Glimmer` component example to Readme

packages/@ember/octane-addon-blueprint/files/tests/dummy/config/optional-features.json
... and also set all optional-features for the dummy, that are set for the app, too.
Super helpful if somebody is installing `ec-addon-docs` afterwards ;)
=> Disable jquery on addon

packages/@ember/octane-addon-blueprint/files/.eslintrc.js, packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/.eslintrc.js, packages/@ember/octane-app-blueprint/files/package.json
It's still a bit different, than classic blueprints - though I'd say I modernized them a bit. Dunno if `excludedFiles` is completely necessary.
However, if installing an addon with this patch applied `ember serve` will work again (is broken at the moment).
=> Unify eslint across app and addon

packages/@ember/octane-app-blueprint/files/config/targets.js
Now the blueprint will use the same `targets` configuration than the default `app` blueprint https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/targets.js
I found the difference when reporting https://github.com/emberjs/ember.js/issues/17678#issuecomment-468885365
cc @NullVoxPopuli
=> Update `config/targets.js` to default configuration

packages/@ember/octane-addon-blueprint/index.js, packages/@ember/octane-addon-blueprint/package.json, packages/@ember/octane-addon-blueprint/yarn.lock, packages/@ember/octane-app-blueprint/index.js, packages/@ember/octane-app-blueprint/package.json, packages/@ember/octane-app-blueprint/yarn.lock, packages/octane-blueprint-utils/index.js, packages/octane-blueprint-utils/package.json, packages/octane-blueprint-utils/yarn.lock
Attempts to grab the latest ember-cli version via an unauthenticated v3 REST API request first (much smaller / faster / better), **BUT** if we hit a 403 error (due to rate limiting) fall back to fetching the tarball (this request is _not_ rate limited) and getting the SHA from that directly.
=> Avoid GitHub rate limiting issues.

packages/@ember/octane-app-blueprint/files/src/resolver.js
The blueprint resolver added 3 custom types:
```
'config': { definitiveCollection: 'main' },
'util': { definitiveCollection: 'utils' },
'component-manager': { definitiveCollection: 'main' },
```
- `config` and `component-manager` are already added with `buildResolverConfig`.
- `util`, we should discuss if the `util` type should be added to the resolver through `buildResolverConfig` or not.
=> Do not add custom types to the default resolver

packages/@ember/octane-addon-blueprint/package.json, packages/@ember/octane-app-blueprint/files/app/router.js, packages/@ember/octane-app-blueprint/package.json
After the [MU removal](https://github.com/ember-cli/ember-octane-blueprint/pull/68), apps generated with the octane app blueprint were not working. This PR fixes it by changing the content of `app/router.js` to be like the official app blueprint. 
Additionally, I have upgraded the package versions. I think when this PR get merged, the packages will automatically be upgraded.
=> Fix `app/router.js` blueprint content

packages/@ember/octane-app-blueprint/index.js
Fixes #93 
@NullVoxPopuli there wasn't any need to update the add blueprint, as it doesn't include `ember-data`.
=> Temporarily pinning ember-data to specific known good SHA

README.md
This is blocked by the `on` modifier RFC / implementation: https://github.com/emberjs/rfcs/pull/471
=> update component example

packages/octane-blueprint-utils/index.js
Fixes the specific error reported in https://github.com/ember-cli/ember-octane-blueprint/issues/96 (reference error when the `got` request fails), but that error is masking some other issue that will need to be tracked down once this lands and is released.
=> Fix mistake in rate limiting error handler.

packages/@ember/octane-app-blueprint/files/config/environment.js
I see the on modifier PR was merged in Ember, so turning the feature flag on here `EMBER_GLIMMER_ON_MODIFIER: true` https://github.com/emberjs/ember.js/pull/17960
=> Enable on modifier feature flag

packages/@ember/octane-app-blueprint/files/package.json, packages/@ember/octane-app-blueprint/index.js
This PR address an issue (reported [here](https://github.com/ember-cli/ember-octane-blueprint/issues/95)) with Ember Data in the current Octane blueprint where there were some issues because the default usage of `fetch` in ember data was still in progress.
This work has now been completed [here](https://github.com/emberjs/data/pull/5900), so we can pin the ember data version to the latest stable release :muscle:
=> pin ember data version to ^3.10.0

packages/@ember/octane-addon-blueprint/files/tests/dummy/app/router.js, packages/@ember/octane-app-blueprint/files/app/router.js
Closes https://github.com/emberjs/ember.js/issues/18166
=> Use native classes in `app/router.js`

packages/@ember/octane-addon-blueprint/files/tests/dummy/app/router.js, packages/@ember/octane-app-blueprint/files/app/router.js
=> Use export default class Router extends EmberRouter {}.

packages/@ember/octane-app-blueprint/files/testem.js
This is causing random test failures, see the [upstream blueprint change](https://github.com/ember-cli/ember-cli/pull/8774/files) for details
=> Remove --disable-gpu flag in testem config

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-addon-blueprint/index.js, packages/@ember/octane-app-blueprint/files/package.json, packages/@ember/octane-app-blueprint/index.js, packages/octane-blueprint-utils/index.js
Using a branch was causing problem for people who had previously ran `yarn install` when the branch was broken, since yarn caches the commit locally indefinitely.
Also renamed the variables since they are not actually URLs.
=> Use git SHA for ember-cli-htmlbars

packages/@ember/octane-addon-blueprint/files/package.json
These modifiers are _specifically_ intended to install when they are needed, not eagerly in all apps/addons.
https://github.com/emberjs/rfcs/blob/master/text/0415-render-element-modifiers.md#official-addon
=> Remove @ember/render-modifiers from addon blueprint.

packages/@ember/octane-addon-blueprint/index.js, packages/@ember/octane-app-blueprint/index.js
This is needed because we want to rely on usage of `@ember/edition-utils`, but that isn't in a published to npm just yet.
=> Use latest ember-source beta tarball.

packages/@ember/octane-app-blueprint/files/config/environment.js
With Ember v3.13.x this property is no longer required to be set to `true`
cc: @pzuraq
=> Remove EMBER_METAL_PROPERTIES from config
