.eslintignore, .eslintrc.js, .npmignore, CONTRIBUTING.md, config/ember-try.js, package.json
=> Upgrade blueprint to ember-cli 3.6

README.md
=> Add `Building/Contributing` readme section

.travis.yml, README.md, packages/@ember/octane-addon-blueprint/package.json, packages/@ember/octane-addon-blueprint/yarn.lock, packages/@ember/octane-app-blueprint/package.json, packages/@ember/octane-app-blueprint/yarn.lock, scripts/verify-publish.sh
resolves: https://github.com/ember-cli/ember-octane-blueprint/issues/28
Also,
- adds publish verification script which will fail the travis build if publish does not succeed (for some reason the deploy step doesn't automatically do this)
=> Support autopublishing of the addon blueprint

packages/@ember/octane-addon-blueprint/files/tests/dummy/config/environment.js, packages/@ember/octane-app-blueprint/files/config/environment.js
Solves the same issue than https://github.com/ember-cli/ember-cli/pull/8433
cc @NullVoxPopuli
=> MU blueprints: enable `EMBER_MODULE_UNIFICATION` feature flag

packages/@ember/octane-addon-blueprint/files/.eslintrc.js, packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-addon-blueprint/index.js, packages/@ember/octane-app-blueprint/files/.eslintrc.js, packages/@ember/octane-app-blueprint/files/package.json, packages/@ember/octane-app-blueprint/index.js
=> Install missing dependencies and settings to make Native Ember works

README.md
Updates the readme to include Glimmer Components, Native Decorators and Tracked Properties.
=> Update README with new available features

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/package.json
Last task discussed at https://github.com/ember-cli/ember-octane-blueprint/issues/41#issuecomment-466042653
cc @NullVoxPopuli
=> Update min version of `ember-cli-babel`

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/package.json
See https://github.com/emberjs/ember.js/pull/17690#issuecomment-468966855
=> downgrade `@ember-decorators/babel-transforms`

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/package.json
Ensures `@action` decorator works.
=> Update minimum version of ember-cli-babel

packages/@ember/octane-addon-blueprint/index.js, packages/@ember/octane-app-blueprint/files/package.json, packages/@ember/octane-app-blueprint/index.js, packages/@ember/octane-app-blueprint/yarn.lock, packages/octane-blueprint-utils/index.js
=> Set latest Ember Data commit version on the app blueprint

packages/@ember/octane-addon-blueprint/files/tests/dummy/config/environment.js, packages/@ember/octane-app-blueprint/files/config/environment.js
Feature flag added in https://github.com/emberjs/ember.js/pull/17735.
=> Add angle bracket invocation for built-ins.

packages/@ember/octane-addon-blueprint/files/tests/dummy/config/environment.js, packages/@ember/octane-app-blueprint/files/config/environment.js
=> add fn feature flag

packages/@ember/octane-app-blueprint/files/app/templates/application.hbs
I just copied this file: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/templates/application.hbs
=> Copy the application.hbs from the classic app blueprint

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/package.json
=> bring in ember-cli-babel bugfix #126

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/package.json
I'm not sure if this is a good idea, but this will fix #137
=> Update for co-location support

packages/@ember/octane-app-blueprint/files/.eslintrc.js, packages/@ember/octane-app-blueprint/files/.travis.yml, packages/@ember/octane-app-blueprint/files/app/app.js, packages/@ember/octane-app-blueprint/files/app/index.html, packages/@ember/octane-app-blueprint/files/app/resolver.js, packages/@ember/octane-app-blueprint/files/app/router.js, packages/@ember/octane-app-blueprint/files/app/templates/application.hbs, packages/@ember/octane-app-blueprint/files/config/environment.js, packages/@ember/octane-app-blueprint/files/gitignore, packages/@ember/octane-app-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/testem.js
re-sync's with app blueprint in ember-cli
=> Resloves #142 - resync app blueprint

packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/package.json
This fixes an incompatibility with Ember 3.13 beta.
=> Update @glimmer/component to 0.14.0-alpha.12

scripts/tests/test-addon-blueprint.sh, scripts/tests/test-app-blueprint.sh
hopefully this'll catch linting issues people have been reporting in fresh apps and addons
=> add linting to ci

packages/@ember/octane-addon-blueprint/files/tests/dummy/app/app.js, packages/@ember/octane-app-blueprint/files/app/app.js
Update app.js files to extend from native classes. 
Fixes: #155
=> Use export default class App extends Application

packages/@ember/octane-app-blueprint/files/package.json, packages/@ember/octane-app-blueprint/index.js
=> Track Ember Data beta

packages/@ember/octane-addon-blueprint/.npmignore, packages/@ember/octane-addon-blueprint/files/.ember-cli.js, packages/@ember/octane-addon-blueprint/files/npmignore, packages/@ember/octane-addon-blueprint/files/package.json, packages/@ember/octane-app-blueprint/files/.ember-cli.js, packages/@ember/octane-app-blueprint/files/package.json
Related to:
* https://github.com/emberjs/data/pull/6452
* https://github.com/emberjs/ember.js/pull/18389
=> Migrate to using @ember/edition-utils.
